### ISSUE TITLE
🐞 - Errors after updating to v 3.50.0 in Angular 14

### ISSUE THREAD

**Issue by atoyansk** [taiga-family/taiga-ui#5732]
### Description

After updating Taiga UI to 3.50.0 version, when I execute ng serve on my application, the following errors are displaying in terminal:

```
Error: node_modules/@taiga-ui/core/directives/hint/hint.directive.d.ts:11:25 - error TS2314: Generic type 'PolymorpheusComponent<T, C>' requires 2 type argument(s).

11     readonly component: PolymorpheusComponent<unknown>;
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@taiga-ui/core/directives/hint/hint.directive.d.ts:19:57 - error TS2314: Generic type 'PolymorpheusComponent<T, C>' requires 2 type argument(s).

19     constructor(el: ElementRef<HTMLElement>, component: PolymorpheusComponent<unknown>, hintService: TuiHintService, options: TuiHintOptions, activeZone?: TuiActiveZoneDirective | null | undefined);
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@taiga-ui/core/interfaces/portal-item.d.ts:6:25 - error TS2314: Generic type 'PolymorpheusComponent<T, C>' requires 2 type argument(s).

6     readonly component: PolymorpheusComponent<any>;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### Angular version

14.0.0

### Taiga UI version

3.50.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Could you try these steps?

- make sure there's no `@tinkoff/ng-polymorpheus` in your `package. Json`
- remove `node_modules`
- remove `package-lock.json`
- do a clean `npm i`

**Comment by atoyansk** [comment]
It fixed! Thanks
